### ISSUE TITLE
Transactions mostly used when are you dealing with multiple save() and if something went wrong, dont save anything(because it might break something in your bissness logic)

### ISSUE THREAD

**Issue by Nazareka** [MaksimMarynau/coffee_shop#5]
https://github.com/MaksimMarynau/coffee_shop/blob/4fa1cafe6577f416f3faf67cc7400f471f75732f/src/coffee_shop_project/coffee_shop_project/apps/coffee_board/views.py#L82

**Comment by MaksimMarynau** [comment]
Hey, i really appreciate your comments, because i am a beginner and a lot of this things in my project i took from different places in the internet- sometimes without any description, what is it and how it must work. I am working on this project and i am going to modify it soon.
